name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Cache Serenity reports
      uses: actions/cache@v3
      with:
        path: target/site/serenity
        key: ${{ runner.os }}-serenity-${{ github.sha }}
        restore-keys: ${{ runner.os }}-serenity-
        
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
    - name: Run tests with Maven
      env:
        CHROME_HEADLESS: true
        WEBDRIVER_CHROME_DRIVER: /usr/bin/google-chrome
      run: mvn clean verify -Dwebdriver.chrome.headless=true
      
    - name: Upload Serenity reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: serenity-reports
        path: target/site/serenity/
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: target/failsafe-reports/
        
    - name: Publish Serenity Report
      uses: actions/upload-pages-artifact@v2
      if: success()
      with:
        path: target/site/serenity/
        
    - name: Setup Pages
      uses: actions/configure-pages@v3
      if: success()
      
    - name: Upload to GitHub Pages
      uses: actions/upload-pages-artifact@v2
      if: success()
      with:
        path: target/site/serenity/ 